### ISSUE TITLE
Elastic SIP Trunking

### ISSUE THREAD

**Issue by timrcoulson** [RJPearson94/twilio-sdk-go#15]
First off, glad to see a great resurrection of Twilio support in go! 👏 

## Is your feature request related to a problem

Looking to Terraform our Elastic SIP Trunking infrastructure on Twilio and have followed the dependency chain here.

https://www.twilio.com/docs/sip-trunking/api

## Describe the solution you'd like

The ability to CRUD:
- SIP trunks
- Origination URIs

## Additional context

I'll undertake the work, unless it's already being worked on.

**Comment by RJPearson94** [comment]
hey @timrcoulson,

It isn't being actively worked on at the moment but I have some time later today/ tomorrow to pick this up. 

Are you using https://github.com/RJPearson94/terraform-provider-twilio? If you are I am happy to pick up this enhancement and the Terraform provider enhancement.

**Comment by timrcoulson** [comment]
Wow that would be fantastic! Also happy to pick up, but will leave you to it if you'd to.

**Comment by RJPearson94** [comment]
Support for SIP trunks and Origination URLs has been merged into master. I want to add support for at least trunking phone number resource before 0.7.0 is released. 

Once it's released I will add support to the Terraform provider https://github.com/RJPearson94/terraform-provider-twilio, I have raised an issue https://github.com/RJPearson94/terraform-provider-twilio/issues/15 to track this

**Comment by RJPearson94** [comment]
V0.7.0 has now been released. So support will be added to the Terraform provider in the coming days

**Comment by RJPearson94** [comment]
The feature has now been added to the Terraform provider and released to the Terraform Registry as part of v0.6.0

**Comment by timrcoulson** [comment]
Awesome - thank you so much for your help! We'll be integrating into our terraform this week 😄

**Comment by RJPearson94** [comment]
No worries @timrcoulson glad I could help. If you have any more feature requests for either the SDK or Provider feel free to raise an issue on the relevant repo
